# Generated by Django 5.2 on 2025-04-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('address', models.CharField()),
                ('citystatezip', models.CharField()),
                ('birthdate', models.DateField()),
                ('phone', models.CharField()),
                ('timezone', models.CharField()),
                ('lat', models.DecimalField(decimal_places=5, max_digits=10)),
                ('long', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderid', models.CharField(primary_key=True, serialize=False)),
                ('customerid', models.CharField()),
                ('ordered', models.DateTimeField()),
                ('shipped', models.DateTimeField()),
                ('total', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('items', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrdersItem',
            fields=[
                ('pk', models.CompositePrimaryKey('orderid', 'sku', blank=True, editable=False, primary_key=True, serialize=False)),
                ('orderid', models.IntegerField()),
                ('sku', models.CharField()),
                ('qty', models.IntegerField()),
                ('unit_price', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'orders_items',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sku', models.CharField(primary_key=True, serialize=False)),
                ('desc', models.CharField(blank=True, null=True)),
                ('wholesale_cost', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('dims_cm', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
