# Generated by Django 5.2 on 2025-04-17 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersitem',
            name='id',
        ),
        migrations.AddField(
            model_name='ordersitem',
            name='pk',
            field=models.CompositePrimaryKey('orderid', 'sku', blank=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='long',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
