# Generated by Django 5.2 on 2025-04-21 22:55
from django.db import migrations


def back_fill_customer_fk(apps, _):
    Customer = apps.get_model("app", "Customer")
    Order = apps.get_model("app", "Order")

    for idx, order in enumerate(Order.objects.all()):
        if idx % 100 == 0:
            print("Progress: ", idx + 1)
        customer = Customer.objects.get(customerid=order.customerid)
        # handle non-existing users due to data corruption
        if customer is None:
            print(f"Cannot find user with id {order.customerid}")
            continue
        order.customer = customer
        order.save()


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_order_customer"),
    ]

    operations = [
        migrations.RunPython(
            back_fill_customer_fk,
            # this allows rewinding the migrations to a previous
            # state by skipping this custom migration script
            reverse_code=migrations.RunPython.noop,
        ),
    ]
