# Generated by Django 5.2 on 2025-04-22 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_auto_20250421_2255"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordersitem",
            name="pk",
        ),
        migrations.AddField(
            model_name="ordersitem",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="ordersitem",
            name="order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="orders_items_fk",
                to="app.order",
            ),
        ),
        migrations.AddField(
            model_name="ordersitem",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="products_fk",
                to="app.product",
            ),
        ),
    ]
